/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayPadolina;

/**
 *
 * @author Aznable
 */
public class Brgy_Indigency extends javax.swing.JPanel {

    /**
     * Creates new form Brgy_Indigency
     */
    public Brgy_Indigency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlTitle1 = new javax.swing.JPanel();
        jLblIcon1 = new javax.swing.JLabel();
        jLblIcon2 = new javax.swing.JLabel();
        jLblRepublic1 = new javax.swing.JLabel();
        jLblProvince1 = new javax.swing.JLabel();
        jLblMunicipal1 = new javax.swing.JLabel();
        jLblPadolinaTitle1 = new javax.swing.JLabel();
        jLblOffice = new javax.swing.JLabel();
        jPnlOfficials1 = new javax.swing.JPanel();
        jLblChairman1 = new javax.swing.JLabel();
        jLblKagawad0 = new javax.swing.JLabel();
        jLblKagawad1 = new javax.swing.JLabel();
        jLblKagawad2 = new javax.swing.JLabel();
        jLblKagawad3 = new javax.swing.JLabel();
        jLblKagawad4 = new javax.swing.JLabel();
        jLblKagawad5 = new javax.swing.JLabel();
        jLblKagawad6 = new javax.swing.JLabel();
        jLblSKchairwoman0 = new javax.swing.JLabel();
        jLblSecretary0 = new javax.swing.JLabel();
        jLablTreasures0 = new javax.swing.JLabel();
        jLblOffice1 = new javax.swing.JLabel();
        jLblBorder = new javax.swing.JLabel();
        jLblTitleClearance0 = new javax.swing.JLabel();
        jLblDate = new javax.swing.JLabel();
        jLblNilalaman0 = new javax.swing.JLabel();
        jLblNilalaman1 = new javax.swing.JLabel();
        jLblCaptainPirma = new javax.swing.JLabel();
        jLblPaalala = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 700));

        jPnlTitle1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/output-onlinepngtools (2).png"))); // NOI18N
        jLblIcon1.setText("asdasd");
        jPnlTitle1.add(jLblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 106));

        jLblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/output-onlinepngtools (3).png"))); // NOI18N
        jLblIcon2.setText("jLabel1");
        jPnlTitle1.add(jLblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 100, 100));

        jLblRepublic1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLblRepublic1.setText("Republic of the Philippines");
        jPnlTitle1.add(jLblRepublic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 159, -1));

        jLblProvince1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLblProvince1.setText("Province of Nueva Ecija ");
        jPnlTitle1.add(jLblProvince1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLblMunicipal1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLblMunicipal1.setText("Municipality of General Tinio ");
        jPnlTitle1.add(jLblMunicipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLblPadolinaTitle1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jLblPadolinaTitle1.setText("<html> <p style=\"color:blue\"> Barangay Padolina </p> </html>");
        jPnlTitle1.add(jLblPadolinaTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 140, 30));

        jLblOffice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLblOffice.setText("OFFICE OF THE BARANGAY CHAIRMAN");
        jPnlTitle1.add(jLblOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 350, 30));

        jPnlOfficials1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPnlOfficials1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblChairman1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblChairman1.setText("<html> <u style=\"color:blue\">Hon. Virgilio B, Domingo.</u><br> <center> Brgy Chairman </center> </br> </html>");
        jPnlOfficials1.add(jLblChairman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 54, -1, -1));

        jLblKagawad0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad0.setText("<html><u style=\"color:blue\"> Hon. Virgilio B, Custodio, Jr.</u> <br> <center> Kagawad </center> </br> </html>");
        jPnlOfficials1.add(jLblKagawad0, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 102, -1, -1));

        jLblKagawad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad1.setText("<html><u style=\"color:blue\">Hon. Bernardo A. Manimbo. </u> <br> <center>Kagawad</center></br></html>");
        jPnlOfficials1.add(jLblKagawad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 150, -1, -1));

        jLblKagawad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad2.setText("<html><u style=\"color:blue\">Hon. Lawrence B. Bote.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 198, -1, -1));

        jLblKagawad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad3.setText("<html><u style=\"color:blue\">Hon. Annie B. Lesmoras.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 246, -1, -1));

        jLblKagawad4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad4.setText("<html><u style=\"color:blue\">Hon. Brigido B. Ramos. Jr.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 294, -1, 34));

        jLblKagawad5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad5.setText("<html><u style=\"color:blue\">Hon. Niel M. Ramos.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 350, -1, 26));

        jLblKagawad6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad6.setText("<html><u style=\"color:blue\">Hon. Nimfa Q. Barlis.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 394, 130, -1));

        jLblSKchairwoman0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblSKchairwoman0.setText("<html><u style=\"color:blue\">Hon. Ela Mea B. Ramos.</u><br><center>SK ChairWoman</br></center></html>");
        jPnlOfficials1.add(jLblSKchairwoman0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 442, -1, -1));

        jLblSecretary0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblSecretary0.setText("<html><u style=\"color:blue\">Fundaver M. Macariola.</u><br><center>Brgy. Secretary</br></center></html>");
        jPnlOfficials1.add(jLblSecretary0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 490, -1, -1));

        jLablTreasures0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLablTreasures0.setText("<html><u style=\"color:blue\">Roselia M. Gonzales.</u><br><center>Brgy. Treasurer</br></center></html>");
        jPnlOfficials1.add(jLablTreasures0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 531, 130, 40));

        jLblOffice1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLblOffice1.setText("<html>BARANGAY OFFICIALS <br><center>2018-2022</br></center></html>");
        jPnlOfficials1.add(jLblOffice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 9, -1, 34));

        jLblBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLblTitleClearance0.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLblTitleClearance0.setText("<html><center>CERTIFICATE OF INDIGENCY</center></html>");

        jLblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLblNilalaman0.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLblNilalaman0.setText("<html>  TO WHOM IT MY CONCERN: <p> <br><br> This is to certify Mr/Ms:____________________, ___________________,y/o, Single/Married/Widow(er), And a bonafide resident of Barangay Padolina, General Tinio, Nueva Ecija and is an indigent member of this community. He/She belongs to low income family...</p></html>");

        jLblNilalaman1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLblNilalaman1.setText("<html><p>This Certification is issued upon the request of Mr/Ms:_______________________, For whatever legal purpose it may serve best.</p></html>");

        jLblCaptainPirma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblCaptainPirma.setText("<html><font size=\"+1\">Virgilio B. Domingo</font><br><center>Barangay Chairman</center></htm>");

        jLblPaalala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLblPaalala.setText("<html><p style=\"color:red\"> This clearance is valid for 6 Months from date of issue and it's not valid without Dry Seal... </p> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPnlOfficials1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLblTitleClearance0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(296, 296, 296)
                                        .addComponent(jLblCaptainPirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLblNilalaman1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblPaalala, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLblNilalaman0, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLblBorder)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPnlOfficials1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLblTitleClearance0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLblNilalaman0, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblNilalaman1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLblCaptainPirma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblPaalala, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLablTreasures0;
    private javax.swing.JLabel jLblBorder;
    private javax.swing.JLabel jLblCaptainPirma;
    private javax.swing.JLabel jLblChairman1;
    private javax.swing.JLabel jLblDate;
    private javax.swing.JLabel jLblIcon1;
    private javax.swing.JLabel jLblIcon2;
    private javax.swing.JLabel jLblKagawad0;
    private javax.swing.JLabel jLblKagawad1;
    private javax.swing.JLabel jLblKagawad2;
    private javax.swing.JLabel jLblKagawad3;
    private javax.swing.JLabel jLblKagawad4;
    private javax.swing.JLabel jLblKagawad5;
    private javax.swing.JLabel jLblKagawad6;
    private javax.swing.JLabel jLblMunicipal1;
    private javax.swing.JLabel jLblNilalaman0;
    private javax.swing.JLabel jLblNilalaman1;
    private javax.swing.JLabel jLblOffice;
    private javax.swing.JLabel jLblOffice1;
    private javax.swing.JLabel jLblPaalala;
    private javax.swing.JLabel jLblPadolinaTitle1;
    private javax.swing.JLabel jLblProvince1;
    private javax.swing.JLabel jLblRepublic1;
    private javax.swing.JLabel jLblSKchairwoman0;
    private javax.swing.JLabel jLblSecretary0;
    private javax.swing.JLabel jLblTitleClearance0;
    private javax.swing.JPanel jPnlOfficials1;
    private javax.swing.JPanel jPnlTitle1;
    // End of variables declaration//GEN-END:variables
}
