/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayPadolina;

/**
 *
 * @author Aznable
 */
public class BrgyBusinessClearanceForm extends javax.swing.JFrame {

    /**
     * Creates new form BrgyBusinessClearanceForm
     */
    public BrgyBusinessClearanceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTxtFullN = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jTxtBName = new javax.swing.JTextField();
        jTxtBusinessA = new javax.swing.JTextField();
        jTxtClearanceNo = new javax.swing.JTextField();
        jLblOwner = new javax.swing.JLabel();
        jLblAddress = new javax.swing.JLabel();
        jLblBName = new javax.swing.JLabel();
        jLblBAddress = new javax.swing.JLabel();
        jLblCNumber = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/x-mark-2-16.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jTxtFullN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFullNActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtFullN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 248, 31));

        jTxtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 248, 31));

        jTxtBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 248, 31));
        jPanel1.add(jTxtBusinessA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 248, 31));

        jTxtClearanceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtClearanceNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtClearanceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 248, 31));

        jLblOwner.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLblOwner.setText("Fullname:");
        jPanel1.add(jLblOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 31));

        jLblAddress.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLblAddress.setText("Address:");
        jPanel1.add(jLblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, 30));

        jLblBName.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLblBName.setText("Business Name:");
        jPanel1.add(jLblBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 30));

        jLblBAddress.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLblBAddress.setText("Business Address:");
        jPanel1.add(jLblBAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        jLblCNumber.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLblCNumber.setText("Clearance No. BPC:");
        jPanel1.add(jLblCNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/printer-4-16.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 111, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Barangay Business Clearance Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new BarangayDashboard().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAddressActionPerformed

    private void jTxtBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBNameActionPerformed

    private void jTxtFullNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFullNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFullNActionPerformed

    private void jTxtClearanceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtClearanceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtClearanceNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrgyBusinessClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrgyBusinessClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrgyBusinessClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrgyBusinessClearanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrgyBusinessClearanceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblAddress;
    private javax.swing.JLabel jLblBAddress;
    private javax.swing.JLabel jLblBName;
    private javax.swing.JLabel jLblCNumber;
    private javax.swing.JLabel jLblOwner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtBName;
    private javax.swing.JTextField jTxtBusinessA;
    private javax.swing.JTextField jTxtClearanceNo;
    private javax.swing.JTextField jTxtFullN;
    // End of variables declaration//GEN-END:variables
}
