/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayPadolina;

/**
 *
 * @author Aznable
 */
public class Business_Clearance extends javax.swing.JPanel {

    /**
     * Creates new form Business_Clearance
     */
    public Business_Clearance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlTitle1 = new javax.swing.JPanel();
        jLblIcon1 = new javax.swing.JLabel();
        jLblIcon2 = new javax.swing.JLabel();
        jLblRepublic1 = new javax.swing.JLabel();
        jLblProvince1 = new javax.swing.JLabel();
        jLblMunicipal1 = new javax.swing.JLabel();
        jLblPadolinaTitle1 = new javax.swing.JLabel();
        jLblOffice = new javax.swing.JLabel();
        jLblBorder = new javax.swing.JLabel();
        jPnlOfficials1 = new javax.swing.JPanel();
        jLblChairman1 = new javax.swing.JLabel();
        jLblKagawad0 = new javax.swing.JLabel();
        jLblKagawad1 = new javax.swing.JLabel();
        jLblKagawad2 = new javax.swing.JLabel();
        jLblKagawad3 = new javax.swing.JLabel();
        jLblKagawad4 = new javax.swing.JLabel();
        jLblKagawad5 = new javax.swing.JLabel();
        jLblKagawad6 = new javax.swing.JLabel();
        jLblSKchairwoman0 = new javax.swing.JLabel();
        jLblSecretary0 = new javax.swing.JLabel();
        jLablTreasures0 = new javax.swing.JLabel();
        jLblOffice1 = new javax.swing.JLabel();
        jLblTitleClearance0 = new javax.swing.JLabel();
        jLblDate = new javax.swing.JLabel();
        jLblNilalaman0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLblCaptainPirma = new javax.swing.JLabel();
        jLblPaalala = new javax.swing.JLabel();
        jLblPaalala1 = new javax.swing.JLabel();

        jPnlTitle1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/output-onlinepngtools (2).png"))); // NOI18N
        jLblIcon1.setText("asdasd");
        jPnlTitle1.add(jLblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 106));

        jLblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/output-onlinepngtools (3).png"))); // NOI18N
        jLblIcon2.setText("jLabel1");
        jPnlTitle1.add(jLblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 100, 106));

        jLblRepublic1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLblRepublic1.setText("Republic of the Philippines");
        jPnlTitle1.add(jLblRepublic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 159, -1));

        jLblProvince1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLblProvince1.setText("Province of Nueva Ecija ");
        jPnlTitle1.add(jLblProvince1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLblMunicipal1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLblMunicipal1.setText("Municipality of General Tinio ");
        jPnlTitle1.add(jLblMunicipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLblPadolinaTitle1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jLblPadolinaTitle1.setText("<html> <p style=\"color:blue\"> Barangay Padolina </p> </html>");
        jPnlTitle1.add(jLblPadolinaTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 140, 30));

        jLblOffice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLblOffice.setText("OFFICE OF THE BARANGAY CHAIRMAN");
        jPnlTitle1.add(jLblOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 350, 30));

        jLblBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jPnlOfficials1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPnlOfficials1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblChairman1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblChairman1.setText("<html> <u style=\"color:blue\">Hon. Virgilio B, Domingo.</u><br> <center> Brgy Chairman </center> </br> </html>");
        jPnlOfficials1.add(jLblChairman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 54, -1, -1));

        jLblKagawad0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad0.setText("<html><u style=\"color:blue\"> Hon. Virgilio B, Custodio, Jr.</u> <br> <center> Kagawad </center> </br> </html>");
        jPnlOfficials1.add(jLblKagawad0, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 102, -1, -1));

        jLblKagawad1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad1.setText("<html><u style=\"color:blue\">Hon. Bernardo A. Manimbo. </u> <br> <center>Kagawad</center></br></html>");
        jPnlOfficials1.add(jLblKagawad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 150, -1, -1));

        jLblKagawad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad2.setText("<html><u style=\"color:blue\">Hon. Lawrence B. Bote.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 198, -1, -1));

        jLblKagawad3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad3.setText("<html><u style=\"color:blue\">Hon. Annie B. Lesmoras.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 246, -1, -1));

        jLblKagawad4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad4.setText("<html><u style=\"color:blue\">Hon. Brigido B. Ramos. Jr.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 294, -1, 34));

        jLblKagawad5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad5.setText("<html><u style=\"color:blue\">Hon. Niel M. Ramos.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 350, -1, 26));

        jLblKagawad6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblKagawad6.setText("<html><u style=\"color:blue\">Hon. Nimfa Q. Barlis.</u><br><center>Kagawad</br></center></html>");
        jPnlOfficials1.add(jLblKagawad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 394, 130, -1));

        jLblSKchairwoman0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblSKchairwoman0.setText("<html><u style=\"color:blue\">Hon. Ela Mea B. Ramos.</u><br><center>SK ChairWoman</br></center></html>");
        jPnlOfficials1.add(jLblSKchairwoman0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 442, -1, -1));

        jLblSecretary0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblSecretary0.setText("<html><u style=\"color:blue\">Fundaver M. Macariola.</u><br><center>Brgy. Secretary</br></center></html>");
        jPnlOfficials1.add(jLblSecretary0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 490, -1, -1));

        jLablTreasures0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLablTreasures0.setText("<html><u style=\"color:blue\">Roselia M. Gonzales.</u><br><center>Brgy. Treasurer</br></center></html>");
        jPnlOfficials1.add(jLablTreasures0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 531, 130, 40));

        jLblOffice1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLblOffice1.setText("<html>BARANGAY OFFICIALS <br><center>2018-2022</br></center></html>");
        jPnlOfficials1.add(jLblOffice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 9, -1, 34));

        jLblTitleClearance0.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLblTitleClearance0.setText("<html><center>BUSINESS CERTIFICATION</center></html>");

        jLblDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLblNilalaman0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblNilalaman0.setText("TO WHOM IT MY CONCERN");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("This Clearances is issued to:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Name Of Owner : _____________________________");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Address : _____________________________");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText(" Business Name : _____________________________");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText(" Business Address : _____________________________");

        jLblCaptainPirma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblCaptainPirma.setText("<html><font size=\"+1\">Virgilio B. Domingo</font><br><center>Barangay Chairman</center></htm>");

        jLblPaalala.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLblPaalala.setText("<html><p style=\"color:red\"> CLEARANCE NO. BPC_______________</p> </html>");

        jLblPaalala1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLblPaalala1.setText("<html><p style=\"color:red\">1. Pursuant to Section 152 of R.A. 7160 (Local Government Code of 1991, no city or municipality may issue any clearance or permit for any business activity unless a clearance is first obtained from barangay where said business is located or conducted. <br> <br> 2. Valid up to December 31, 2021</p> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLblBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlOfficials1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblCaptainPirma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblNilalaman0, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jLblTitleClearance0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblPaalala, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLblPaalala1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblBorder)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPnlOfficials1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLblTitleClearance0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLblNilalaman0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67)
                        .addComponent(jLblCaptainPirma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblPaalala, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblPaalala1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLablTreasures0;
    private javax.swing.JLabel jLblBorder;
    private javax.swing.JLabel jLblCaptainPirma;
    private javax.swing.JLabel jLblChairman1;
    private javax.swing.JLabel jLblDate;
    private javax.swing.JLabel jLblIcon1;
    private javax.swing.JLabel jLblIcon2;
    private javax.swing.JLabel jLblKagawad0;
    private javax.swing.JLabel jLblKagawad1;
    private javax.swing.JLabel jLblKagawad2;
    private javax.swing.JLabel jLblKagawad3;
    private javax.swing.JLabel jLblKagawad4;
    private javax.swing.JLabel jLblKagawad5;
    private javax.swing.JLabel jLblKagawad6;
    private javax.swing.JLabel jLblMunicipal1;
    private javax.swing.JLabel jLblNilalaman0;
    private javax.swing.JLabel jLblOffice;
    private javax.swing.JLabel jLblOffice1;
    private javax.swing.JLabel jLblPaalala;
    private javax.swing.JLabel jLblPaalala1;
    private javax.swing.JLabel jLblPadolinaTitle1;
    private javax.swing.JLabel jLblProvince1;
    private javax.swing.JLabel jLblRepublic1;
    private javax.swing.JLabel jLblSKchairwoman0;
    private javax.swing.JLabel jLblSecretary0;
    private javax.swing.JLabel jLblTitleClearance0;
    private javax.swing.JPanel jPnlOfficials1;
    private javax.swing.JPanel jPnlTitle1;
    // End of variables declaration//GEN-END:variables
}
