/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayPadolina;

import com.github.sarxos.webcam.Webcam;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 63926ppppppppp
 */
public class Residence extends javax.swing.JFrame {

    /**
     * Creates new form Residence
     */

Webcam wc;

    public Residence() {
        initComponents();
        jBtnRDelete.setVisible(true);
        jBtnEdit.setVisible(true);
        wc = Webcam.getDefault();
        popPurok();
        showAllResidence();
//        wc.setViewSize(WebcamResolution.VGA.getSize());Q#@$@$Q
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTxtFN = new javax.swing.JTextField();
        jTxtMaiden = new javax.swing.JTextField();
        jChckMale = new javax.swing.JCheckBox();
        jChckFemale = new javax.swing.JCheckBox();
        jTxtSN = new javax.swing.JTextField();
        jTxtRel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtPOB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtContactNo = new javax.swing.JTextField();
        jTxtHN = new javax.swing.JTextField();
        jlbl_profile = new javax.swing.JLabel();
        jBttnCap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_residents = new javax.swing.JTable();
        jBtnRAdd = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnRDelete = new javax.swing.JButton();
        jTxtDOB = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLblPurok = new javax.swing.JLabel();
        jCmbPurok = new javax.swing.JComboBox<>();
        jTxtCit = new javax.swing.JTextField();
        jCmbCivStat = new javax.swing.JComboBox<>();
        jRdYes = new javax.swing.JRadioButton();
        jRdNo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNActionPerformed(evt);
            }
        });
        jTxtFN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFNKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, 30));
        jPanel1.add(jTxtMaiden, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 160, 30));

        jChckMale.setBackground(new java.awt.Color(102, 204, 255));
        buttonGroup1.add(jChckMale);
        jChckMale.setText("Male");
        jChckMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChckMaleActionPerformed(evt);
            }
        });
        jPanel1.add(jChckMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, 30));

        jChckFemale.setBackground(new java.awt.Color(102, 204, 255));
        buttonGroup1.add(jChckFemale);
        jChckFemale.setText("Female");
        jChckFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChckFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(jChckFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, 30));

        jTxtSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSNActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 30));

        jTxtRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRelActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtRel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 160, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Maiden Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 70, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Gender:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Citizenship:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 70, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Religion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 50, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Civil Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 70, 30));

        jTxtPOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPOBActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtPOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("DOB:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 30, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("POB:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 30, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Contact Number:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("House Number:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 90, 30));

        jTxtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContactNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 160, 30));
        jPanel1.add(jTxtHN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 160, 30));

        jlbl_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jlbl_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 120));

        jBttnCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/compact-camera-16.png"))); // NOI18N
        jBttnCap.setText("TAKE");
        jBttnCap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBttnCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCapActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));

        jtbl_residents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fullname", "Gender", "Citizenship", "Religion", "Civil Status", "DOB", "POB", "Contact.No", "House #", "Purok Name", "Registered Voter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_residents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_residentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_residents);
        if (jtbl_residents.getColumnModel().getColumnCount() > 0) {
            jtbl_residents.getColumnModel().getColumn(0).setMinWidth(50);
            jtbl_residents.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtbl_residents.getColumnModel().getColumn(0).setMaxWidth(50);
            jtbl_residents.getColumnModel().getColumn(1).setMinWidth(150);
            jtbl_residents.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtbl_residents.getColumnModel().getColumn(1).setMaxWidth(150);
            jtbl_residents.getColumnModel().getColumn(9).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 770, 210));

        jBtnRAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/add-user-16.png"))); // NOI18N
        jBtnRAdd.setText("ADD");
        jBtnRAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnRAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, 30));

        jBtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/edit-4-16.png"))); // NOI18N
        jBtnEdit.setText("UPDATE");
        jBtnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 120, 30));

        jBtnRDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/disapprove-16.png"))); // NOI18N
        jBtnRDelete.setText("DELETE");
        jBtnRDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnRDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 120, 30));
        jPanel1.add(jTxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 160, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/x-mark-2-16.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 40, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("RESIDENCE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 420, 60));

        jLblPurok.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLblPurok.setText("Purok:");
        jPanel1.add(jLblPurok, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jCmbPurok.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCmbPurok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbPurokActionPerformed(evt);
            }
        });
        jPanel1.add(jCmbPurok, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 160, 30));

        jTxtCit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCitActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtCit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, 30));

        jCmbCivStat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCmbCivStat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Widow" }));
        jCmbCivStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCivStatActionPerformed(evt);
            }
        });
        jPanel1.add(jCmbCivStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 160, 30));

        buttonGroup2.add(jRdYes);
        jRdYes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRdYes.setText("Yes");
        jRdYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdYesActionPerformed(evt);
            }
        });
        jPanel1.add(jRdYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        buttonGroup2.add(jRdNo);
        jRdNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRdNo.setText("No");
        jRdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdNoActionPerformed(evt);
            }
        });
        jPanel1.add(jRdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Voter");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new BarangayDashboard().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxtFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNActionPerformed

    private void jChckFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChckFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChckFemaleActionPerformed

    private void jTxtSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSNActionPerformed

    private void jTxtRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRelActionPerformed

    private void jTxtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContactNoActionPerformed

    private void jTxtPOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPOBActionPerformed

    private void jBttnCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCapActionPerformed
         if (jBttnCap.getText().equals("TAKE")) {
            wc.open();
            jBttnCap.setText("CAPTURE");
            new VideoFeeder().start();
        }else{
             try {
             //JOptionPane.showMessageDialog(this,new SimpleDateFormat("HH_mm_ss").format(jTxtDOB.getDate())); 
                 ImageIO.write(wc.getImage(), "JPG", new File("src/Images/" + jTxtFN.getText() +  jTxtSN.getText()+ new SimpleDateFormat("HH_mm_ss").format(jTxtDOB.getDate()) + ".jpg"));
                 wc.close();
                 jBttnCap.setText("TAKE");
             } catch (IOException ex) {
                 java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jBttnCapActionPerformed

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
         
        Date petsanow = new Date();
        int taon  = 0;
      if(jTxtDOB.getDate() != null){
         taon =   petsanow.getYear() -   jTxtDOB.getDate().getYear();
         if(petsanow.getMonth() > jTxtDOB.getDate().getMonth() ){
                taon -=1;
            
            }
      }
        if (jlbl_profile.getIcon() == null || jTxtFN.getText().isBlank() || jTxtMaiden.getText().isBlank() || jTxtSN.getText().isBlank() || !(jChckMale.isSelected() || jChckFemale.isSelected()) || jTxtCit.getText().isBlank() || jTxtRel.getText().isBlank() || jTxtDOB.getDate() == null || jTxtPOB.getText().isBlank() || jTxtContactNo.getText().isBlank() || jTxtHN.getText().isBlank() || !(jRdYes.isSelected() || jRdNo.isSelected())){
               JOptionPane.showMessageDialog(this,"Please Fill up all information and check the picture "); 
        } else if(petsanow.getTime() < jTxtDOB.getDate().getTime() ){
               JOptionPane.showMessageDialog(this,"Not yet born!"); 
        }
        else if(taon <18 && jRdYes.isSelected()){
               JOptionPane.showMessageDialog(this,"Not Yet Qualified to Vote"); 

  
        }else{
               //JOptionPane.showMessageDialog(this,"Update"); 
          updateResident(selectedData);
    }//GEN-LAST:event_jBtnEditActionPerformed
  }
    private void jBtnRAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRAddActionPerformed
        
        Date petsanow = new Date();
        int taon  = 0;
      if(jTxtDOB.getDate() != null){
         taon =   petsanow.getYear() -   jTxtDOB.getDate().getYear();
         if(petsanow.getMonth() > jTxtDOB.getDate().getMonth() ){
                taon -=1;
            
            }
      }
        if (jlbl_profile.getIcon() == null || jTxtFN.getText().isBlank() || jTxtMaiden.getText().isBlank() || jTxtSN.getText().isBlank() || !(jChckMale.isSelected() || jChckFemale.isSelected()) || jTxtCit.getText().isBlank() || jTxtRel.getText().isBlank() || jTxtDOB.getDate() == null || jTxtPOB.getText().isBlank() || jTxtContactNo.getText().isBlank() || jTxtHN.getText().isBlank() || !(jRdYes.isSelected() || jRdNo.isSelected())){
               JOptionPane.showMessageDialog(this,"Please Fill up all information and check the picture "); 
        } else if(petsanow.getTime() < jTxtDOB.getDate().getTime() ){
               JOptionPane.showMessageDialog(this,"Not yet born!"); 
        }
        else if(taon <18 && jRdYes.isSelected()){
               JOptionPane.showMessageDialog(this,"Not Yet Qualified to Vote"); 

  
        }else{
               //JOptionPane.showMessageDialog(this,"Add"); 
         addResident();
        }
        
    }//GEN-LAST:event_jBtnRAddActionPerformed
    
    int selectedData;
    
    private void jtbl_residentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_residentsMouseClicked
        selectedData = Integer.parseInt(jtbl_residents.getValueAt(jtbl_residents.getSelectedRow(),0).toString());
        fetchSelectedResident(selectedData);
        jBtnRAdd.setVisible(true);
        jBtnRDelete.setVisible(true);
        jBtnEdit.setVisible(true);
    }//GEN-LAST:event_jtbl_residentsMouseClicked

    private void jBtnRDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRDeleteActionPerformed
        deleteResident(selectedData);
    }//GEN-LAST:event_jBtnRDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new BarangayDashboard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtFNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFNKeyTyped
        char c = evt.getKeyChar();
          if (!((c >= 'A') && (c <= 'Z') || (c >= 'a') && (c <= 'z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }
    }//GEN-LAST:event_jTxtFNKeyTyped

    private void jTxtCitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCitActionPerformed

    private void jCmbPurokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbPurokActionPerformed
//        int index =  jCmbPurok.getSelectedIndex();
//        if(index == 0){
//         printReceipt(new BrgyClearance());
//        }
    }//GEN-LAST:event_jCmbPurokActionPerformed

    private void jRdYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdYesActionPerformed

    private void jRdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdNoActionPerformed

    private void jChckMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChckMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChckMaleActionPerformed

    private void jCmbCivStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCivStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbCivStatActionPerformed
    
    SqlConnection getDBConn = new SqlConnection();
    Connection connection = getDBConn.DbconnectP();
    
    private void showAllResidence(){
    try {
        DefaultTableModel model = (DefaultTableModel)jtbl_residents.getModel();
        Object[] rows = new Object[15];
        String LoginQuery = "SELECT * FROM resident";
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery(LoginQuery);
        String gender;
        
        while(rs.next()){
            String fullname = rs.getString("first_name") + " " + rs.getString("middle_name") + " " + rs.getString("last_name");
            rows[0] = rs.getInt("id");
            rows[1] = fullname;
            int gen = Integer.parseInt(rs.getString("gender"));
            if (gen==0) {
                gender="Male";
            }else{
                gender="Female";
            }
            rows[2] = gender;
            rows[3] = rs.getString("citizenship");
            rows[4] = rs.getString("religion");
            rows[5] = rs.getString("civil_stat");
            rows[6] = rs.getString("DoB");
            rows[7] = rs.getString("PoB");
            rows[8] = rs.getString("contact_num");
            rows[9] = rs.getString("house_num");
            rows[10] = rs.getString("purok_name");
            rows[11] = rs.getInt("IsVoter");
            model.addRow(rows);
            
        }
        
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }
    
    void popPurok(){
        try {
        String LoginQuery = "SELECT * FROM puroks";
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery(LoginQuery);
       
        
        
        
        while(rs.next()){
            jCmbPurok.addItem(rs.getString("purok_descrip"));
           
        }
        
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    }
    
    
    private void fetchSelectedResident(int ids){
    try {
        String LoginQuery = "SELECT * FROM resident where id = '"+ids+"'";
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery(LoginQuery);
        String gender;
        
        while(rs.next()){
            String fullname = rs.getString("first_name") + " " + rs.getString("middle_name") + " " + rs.getString("last_name");
            jTxtFN.setText(rs.getString("first_name"));
            jTxtMaiden.setText(rs.getString("middle_name"));
            jTxtSN.setText(rs.getString("last_name"));
            int gen = Integer.parseInt(rs.getString("gender"));
            if (gen==0) {
                jChckMale.setSelected(true);
            }else{
                jChckFemale.setSelected(true);
            }
            jTxtCit.setText(rs.getString("citizenship"));
            jTxtRel.setText(rs.getString("religion"));
              String stat = rs.getString("civil_stat");
            jCmbCivStat.setSelectedItem(stat);
            jTxtDOB.setDate(rs.getDate("DoB"));
           jTxtPOB.setText(rs.getString("PoB"));
           int vote = rs.getInt("IsVoter");
            if (vote==0) {
                jRdNo.setSelected(true);
            }else{
                jRdYes.setSelected(true);
            }
           jTxtContactNo.setText(rs.getString("contact_num"));
           jTxtHN.setText(rs.getString("house_num"));
           String prof = rs.getString("profile");
           JOptionPane.showMessageDialog(this,prof);
           ImageIcon imgs = new ImageIcon(getClass().getResource("/Images/"+prof+""));
//           JOptionPane.showMessageDialog(this,imgs);
           jlbl_profile.setIcon(imgs);
        }
        
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }
    
    public void deleteFormContent(){
        jTxtFN.setText("");
        jTxtMaiden.setText("");
        jTxtSN.setText("");
        jTxtDOB.setDate(null);
        jTxtCit.setText("");
        jTxtRel.setText("");
        jCmbCivStat.setSelectedIndex(0);
        jTxtPOB.setText("");
        jTxtContactNo.setText("");
        jTxtHN.setText("");
    }
    
        int gender;
    private void addResident(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String strDate = dateFormat.format(jTxtDOB.getDate());
    try {
        String addresident = "INSERT INTO `resident` (`first_name`, `middle_name`, `last_name`, `gender`, `DoB`, `PoB`, `civil_stat`, `citizenship`, `religion`,`contact_num`, `purok_name`, `house_num`, `profile`,`IsVoter`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement st = connection.prepareStatement(addresident);
        st.setString(1, jTxtFN.getText());
        st.setString(2, jTxtMaiden.getText());
        st.setString(3, jTxtSN.getText());
          if (jChckMale.isSelected()) {
              gender=0;
        }else if (jChckFemale.isSelected()) {
            gender=1;
        }
        st.setInt(4, gender);
        st.setString(5, strDate);
        st.setString(6, jTxtPOB.getText());
        st.setString(7, jCmbCivStat.getSelectedItem().toString());
        st.setString(8, jTxtCit.getText());
        st.setString(9, jTxtRel.getText());
        st.setString(10, jTxtContactNo.getText());
        st.setString(11, jCmbPurok.getSelectedItem().toString());
        st.setString(12, jTxtHN.getText());
        st.setString(13, jTxtFN.getText() +  jTxtSN.getText()+ new SimpleDateFormat("HH_mm_ss").format(jTxtDOB.getDate()) + ".jpg");
        if (jRdYes.isSelected()) {
           st.setInt(14, 1);
        }else if (jRdNo.isSelected()) {
            st.setInt(14, 0);
        }
        int i = st.executeUpdate();
        if (i > 0) {
            JOptionPane.showMessageDialog(this,"Successfully Added");
//            tanggalinAngLamanNgPosition();
            DefaultTableModel mod = (DefaultTableModel)jtbl_residents.getModel();
            mod.setRowCount(0);
            showAllResidence();
            deleteFormContent();
            jBtnRDelete.setVisible(false);
            jBtnEdit.setVisible(false);
            jBtnRAdd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,"Error");
        }
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }
    
    public void updateResident(int id){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String strDate = dateFormat.format(jTxtDOB.getDate());
         try {
            String addresident = "UPDATE `resident` SET `first_name` = ?, `middle_name`= ?, `last_name`= ?, `gender`= ?, `DoB`= ?, `PoB`= ?, `civil_stat`= ?, `citizenship`= ?, `religion`= ?,`contact_num`= ?, `purok_name`= ?, `house_num`= ?, `profile`= ?, `IsVoter`=? WHERE id =?";
            PreparedStatement st = connection.prepareStatement(addresident);
            st.setString(1, jTxtFN.getText());
            st.setString(2, jTxtMaiden.getText());
            st.setString(3, jTxtSN.getText());
              if (jChckMale.isSelected()) {
                  gender=0;
            }else if (jChckFemale.isSelected()) {
                gender=1;
            }
            st.setInt(4, gender);
            st.setString(5,strDate );
            st.setString(6, jTxtPOB.getText());
            st.setString(7, jCmbCivStat.getSelectedItem().toString());
            st.setString(8, jTxtCit.getText());
            st.setString(9, jTxtRel.getText());
            st.setString(10, jTxtContactNo.getText());
            st.setString(11, jCmbPurok.getSelectedItem().toString());
            st.setString(12, jTxtHN.getText());
            st.setString(13, jTxtFN.getText() +  jTxtSN.getText()+ new SimpleDateFormat("HH_mm_ss").format(jTxtDOB.getDate()) + ".jpg");
            if (jRdYes.isSelected()) {
           st.setInt(14, 1);
        }else if (jRdNo.isSelected()) {
            st.setInt(14, 0);
        }
            st.setInt(15,id);
           // JOptionPane.showMessageDialog(this,"d2");
            int i = st.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(this,"Successfully Updated");
                DefaultTableModel mod = (DefaultTableModel)jtbl_residents.getModel();
                mod.setRowCount(0);
                showAllResidence();
                deleteFormContent();
                jBtnRDelete.setVisible(false);
                jBtnEdit.setVisible(false);
                jBtnRAdd.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    
    public void deleteResident(int id){
         try {
            String Deleteresident = "DELETE FROM resident WHERE id =?";
            PreparedStatement st = connection.prepareStatement(Deleteresident);
            st.setInt(1,id);
            int i = st.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(this,"Successfully Deleted");
    //            tanggalinAngLamanNgPosition();
                DefaultTableModel mod = (DefaultTableModel)jtbl_residents.getModel();
                mod.setRowCount(0);
                showAllResidence();
                deleteFormContent();
                jBtnRDelete.setVisible(false);
                jBtnEdit.setVisible(false);
                jBtnRAdd.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Residence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jBtnRAdd;
    private javax.swing.JButton jBtnRDelete;
    private javax.swing.JButton jBttnCap;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChckFemale;
    private javax.swing.JCheckBox jChckMale;
    private javax.swing.JComboBox<String> jCmbCivStat;
    private javax.swing.JComboBox<String> jCmbPurok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblPurok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRdNo;
    private javax.swing.JRadioButton jRdYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCit;
    private javax.swing.JTextField jTxtContactNo;
    private com.toedter.calendar.JDateChooser jTxtDOB;
    private javax.swing.JTextField jTxtFN;
    private javax.swing.JTextField jTxtHN;
    private javax.swing.JTextField jTxtMaiden;
    private javax.swing.JTextField jTxtPOB;
    private javax.swing.JTextField jTxtRel;
    private javax.swing.JTextField jTxtSN;
    private javax.swing.JLabel jlbl_profile;
    private javax.swing.JTable jtbl_residents;
    // End of variables declaration//GEN-END:variables

     Image img;
    
    class VideoFeeder extends Thread {
    
          public void run(){
          
               while(true){
                   img = wc.getImage();
                   jlbl_profile.setIcon(new ImageIcon(img));
//                       Thread.sleep(5000);
                }
          
          }
    
    }
    
   }
