/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayPadolina;

import com.github.sarxos.webcam.Webcam;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 63926ppppppppp
 */
public class Residence extends javax.swing.JFrame {

    /**
     * Creates new form Residence
     */

Webcam wc;

    public Residence() {
        initComponents();
        jBtnRDelete.setVisible(false);
        jBtnEdit.setVisible(false);
        wc = Webcam.getDefault();
        showAllResidence();
//        wc.setViewSize(WebcamResolution.VGA.getSize());Q#@$@$Q
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTxtFN = new javax.swing.JTextField();
        jTxtMaiden = new javax.swing.JTextField();
        jTxtCit = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTxtSN = new javax.swing.JTextField();
        jTxtRel = new javax.swing.JTextField();
        jTxtCivStat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtPOB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtContactNo = new javax.swing.JTextField();
        jTxtHN = new javax.swing.JTextField();
        jlbl_profile = new javax.swing.JLabel();
        jBttnCap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_residents = new javax.swing.JTable();
        jBtnRAdd = new javax.swing.JButton();
        jBtnEdit = new javax.swing.JButton();
        jBtnRDelete = new javax.swing.JButton();
        jTxtDOB = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFNActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 30));
        jPanel1.add(jTxtMaiden, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 30));

        jTxtCit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCitActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtCit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 160, 30));

        jCheckBox1.setBackground(new java.awt.Color(102, 204, 255));
        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Male");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, 30));

        jCheckBox2.setBackground(new java.awt.Color(102, 204, 255));
        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Female");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 30));

        jTxtSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSNActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 30));

        jTxtRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRelActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtRel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 160, 30));

        jTxtCivStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCivStatActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtCivStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 160, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Maiden Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Gender:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 60, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Citizenship:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 70, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Religion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 50, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Civil Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 70, 30));

        jTxtPOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPOBActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtPOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 160, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("DOB:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 30, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("POB:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 30, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Contact Number:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("House Number:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 30));

        jTxtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContactNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 160, 30));
        jPanel1.add(jTxtHN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 160, 30));

        jlbl_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jlbl_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 120));

        jBttnCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/compact-camera-16.png"))); // NOI18N
        jBttnCap.setText("TAKE");
        jBttnCap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBttnCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCapActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, -1));

        jtbl_residents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fullname", "Gender", "Citizenship", "Religion", "Civil Status", "DOB", "POB", "Contact.No", "House #", "Purok ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_residents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_residentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_residents);
        if (jtbl_residents.getColumnModel().getColumnCount() > 0) {
            jtbl_residents.getColumnModel().getColumn(0).setMinWidth(50);
            jtbl_residents.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtbl_residents.getColumnModel().getColumn(0).setMaxWidth(50);
            jtbl_residents.getColumnModel().getColumn(1).setMinWidth(150);
            jtbl_residents.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtbl_residents.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 940, -1));

        jBtnRAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/add-user-16.png"))); // NOI18N
        jBtnRAdd.setText("ADD");
        jBtnRAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnRAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 120, 30));

        jBtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/edit-4-16.png"))); // NOI18N
        jBtnEdit.setText("UPDATE");
        jBtnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 120, 30));

        jBtnRDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/disapprove-16.png"))); // NOI18N
        jBtnRDelete.setText("DELETE");
        jBtnRDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnRDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 120, 30));
        jPanel1.add(jTxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 160, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BrgyLogo/x-mark-2-16.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new BarangayDashboard().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxtFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFNActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jTxtSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSNActionPerformed

    private void jTxtRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRelActionPerformed

    private void jTxtCivStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCivStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCivStatActionPerformed

    private void jTxtCitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCitActionPerformed

    private void jTxtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContactNoActionPerformed

    private void jTxtPOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPOBActionPerformed

    private void jBttnCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCapActionPerformed
         if (jBttnCap.getText().equals("TAKE")) {
            wc.open();
            jBttnCap.setText("CAPTURE");
            new VideoFeeder().start();
        }else{
             try {
                 ImageIO.write(wc.getImage(), "JPG", new File("src/Images/" + jTxtFN.getText() + ".jpg"));
                 wc.close();
             } catch (IOException ex) {
                 java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jBttnCapActionPerformed

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        updateResident(selectedData);
    }//GEN-LAST:event_jBtnEditActionPerformed

    private void jBtnRAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRAddActionPerformed
        addResident();
    }//GEN-LAST:event_jBtnRAddActionPerformed
    
    int selectedData;
    
    private void jtbl_residentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_residentsMouseClicked
        selectedData = Integer.parseInt(jtbl_residents.getValueAt(jtbl_residents.getSelectedRow(),0).toString());
        fetchSelectedResident(selectedData);
        jBtnRAdd.setVisible(false);
        jBtnRDelete.setVisible(true);
        jBtnEdit.setVisible(true);
    }//GEN-LAST:event_jtbl_residentsMouseClicked

    private void jBtnRDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRDeleteActionPerformed
        deleteResident(selectedData);
    }//GEN-LAST:event_jBtnRDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new BarangayDashboard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    SqlConnection getDBConn = new SqlConnection();
    Connection connection = getDBConn.DbconnectP();
    
    private void showAllResidence(){
    try {
        DefaultTableModel model = (DefaultTableModel)jtbl_residents.getModel();
        Object[] rows = new Object[15];
        String LoginQuery = "SELECT * FROM resident";
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery(LoginQuery);
        String gender;
        
        while(rs.next()){
            String fullname = rs.getString("first_name") + " " + rs.getString("middle_name") + " " + rs.getString("last_name");
            rows[0] = rs.getInt("id");
            rows[1] = fullname;
            int gen = Integer.parseInt(rs.getString("gender"));
            if (gen==0) {
                gender="Male";
            }else{
                gender="Female";
            }
            rows[2] = gender;
            rows[3] = rs.getString("citizenship");
            rows[4] = rs.getString("religion");
            rows[5] = rs.getString("civil_stat");
            rows[6] = rs.getString("DoB");
            rows[7] = rs.getString("PoB");
//            rows[8] = rs.getString("occupation");
            rows[8] = rs.getString("contact_num");
            rows[9] = rs.getString("house_num");
            rows[10] = rs.getInt("purok_id");
            model.addRow(rows);
            
        }
        
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }
    
    private void fetchSelectedResident(int ids){
    try {
        String LoginQuery = "SELECT * FROM resident where id = '"+ids+"'";
        Statement st = connection.createStatement();
        ResultSet rs = st.executeQuery(LoginQuery);
        String gender;
        
        while(rs.next()){
            String fullname = rs.getString("first_name") + " " + rs.getString("middle_name") + " " + rs.getString("last_name");
            jTxtFN.setText(rs.getString("first_name"));
            jTxtMaiden.setText(rs.getString("middle_name"));
            jTxtSN.setText(rs.getString("last_name"));
            int gen = Integer.parseInt(rs.getString("gender"));
            if (gen==0) {
                jCheckBox1.setSelected(true);
            }else{
                jCheckBox2.setSelected(true);
            }
            jTxtCit.setText(rs.getString("citizenship"));
            jTxtRel.setText(rs.getString("religion"));
            jTxtCivStat.setText(rs.getString("civil_stat"));
            jTxtDOB.setDate(rs.getDate("DoB"));
           jTxtPOB.setText(rs.getString("PoB"));
           jTxtContactNo.setText(rs.getString("contact_num"));
           jTxtHN.setText(rs.getString("house_num"));
           String prof = rs.getString("profile");
           ImageIcon imgs = new ImageIcon(getClass().getResource("/Images/Pictures/"+prof+".jpg"));
           jlbl_profile.setIcon(imgs);
        }
        
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }
    
    public void deleteFormContent(){
        jTxtFN.setText("");
        jTxtMaiden.setText("");
        jTxtSN.setText("");
        jTxtDOB.setDate(null);
        jTxtCit.setText("");
        jTxtRel.setText("");
        jTxtCivStat.setText("");
        jTxtPOB.setText("");
        jTxtContactNo.setText("");
        jTxtHN.setText("");
    }
    
        int gender;
    private void addResident(){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String strDate = dateFormat.format(jTxtDOB.getDate());
    try {
        String addresident = "INSERT INTO `resident` (`first_name`, `middle_name`, `last_name`, `gender`, `DoB`, `PoB`, `civil_stat`, `citizenship`, `religion`,`contact_num`, `purok_id`, `house_num`, `profile`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement st = connection.prepareStatement(addresident);
        st.setString(1, jTxtFN.getText());
        st.setString(2, jTxtMaiden.getText());
        st.setString(3, jTxtSN.getText());
          if (jCheckBox1.isSelected()) {
              gender=0;
        }else if (jCheckBox2.isSelected()) {
            gender=1;
        }
        st.setInt(4, gender);
        st.setString(5, strDate);
        st.setString(6, jTxtPOB.getText());
        st.setString(7, jTxtCivStat.getText());
        st.setString(8, jTxtCit.getText());
        st.setString(9, jTxtRel.getText());
        st.setString(10, jTxtContactNo.getText());
        st.setInt(11, 1);
        st.setString(12, jTxtHN.getText());
        st.setString(13, jTxtFN.getText()+".jpg");
        int i = st.executeUpdate();
        if (i > 0) {
            JOptionPane.showMessageDialog(this,"Successfully Added");
//            tanggalinAngLamanNgPosition();
            DefaultTableModel mod = (DefaultTableModel)jtbl_residents.getModel();
            mod.setRowCount(0);
            showAllResidence();
            deleteFormContent();
            jBtnRDelete.setVisible(false);
            jBtnEdit.setVisible(false);
            jBtnRAdd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,"Error");
        }
    } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    }
    
    public void updateResident(int id){
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String strDate = dateFormat.format(jTxtDOB.getDate());
         try {
            String addresident = "UPDATE `resident` SET `first_name` = ?, `middle_name`= ?, `last_name`= ?, `gender`= ?, `DoB`= ?, `PoB`= ?, `civil_stat`= ?, `citizenship`= ?, `religion`= ?,`contact_num`= ?, `purok_id`= ?, `house_num`= ?, `profile`= ? WHERE id =?";
            PreparedStatement st = connection.prepareStatement(addresident);
            st.setString(1, jTxtFN.getText());
            st.setString(2, jTxtMaiden.getText());
            st.setString(3, jTxtSN.getText());
              if (jCheckBox1.isSelected()) {
                  gender=0;
            }else if (jCheckBox2.isSelected()) {
                gender=1;
            }
            st.setInt(4, gender);
            st.setString(5,strDate );
            st.setString(6, jTxtPOB.getText());
            st.setString(7, jTxtCivStat.getText());
            st.setString(8, jTxtCit.getText());
            st.setString(9, jTxtRel.getText());
            st.setString(10, jTxtContactNo.getText());
            st.setInt(11, 1);
            st.setString(12, jTxtHN.getText());
            st.setString(13, jTxtFN.getText()+".jpg");
            st.setInt(14,id);
            int i = st.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(this,"Successfully Added");
    //            tanggalinAngLamanNgPosition();
                DefaultTableModel mod = (DefaultTableModel)jtbl_residents.getModel();
                mod.setRowCount(0);
                showAllResidence();
                deleteFormContent();
                jBtnRDelete.setVisible(false);
                jBtnEdit.setVisible(false);
                jBtnRAdd.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    
    public void deleteResident(int id){
         try {
            String Deleteresident = "DELETE FROM resident WHERE id =?";
            PreparedStatement st = connection.prepareStatement(Deleteresident);
            st.setInt(1,id);
            int i = st.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(this,"Successfully Deleted");
    //            tanggalinAngLamanNgPosition();
                DefaultTableModel mod = (DefaultTableModel)jtbl_residents.getModel();
                mod.setRowCount(0);
                showAllResidence();
                deleteFormContent();
                jBtnRDelete.setVisible(false);
                jBtnEdit.setVisible(false);
                jBtnRAdd.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,"Error");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Residence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Residence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JButton jBtnRAdd;
    private javax.swing.JButton jBtnRDelete;
    private javax.swing.JButton jBttnCap;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCit;
    private javax.swing.JTextField jTxtCivStat;
    private javax.swing.JTextField jTxtContactNo;
    private com.toedter.calendar.JDateChooser jTxtDOB;
    private javax.swing.JTextField jTxtFN;
    private javax.swing.JTextField jTxtHN;
    private javax.swing.JTextField jTxtMaiden;
    private javax.swing.JTextField jTxtPOB;
    private javax.swing.JTextField jTxtRel;
    private javax.swing.JTextField jTxtSN;
    private javax.swing.JLabel jlbl_profile;
    private javax.swing.JTable jtbl_residents;
    // End of variables declaration//GEN-END:variables

     Image img;
    
    class VideoFeeder extends Thread {
    
          public void run(){
          
               while(true){
                   img = wc.getImage();
                   jlbl_profile.setIcon(new ImageIcon(img));
//                       Thread.sleep(5000);
                }
          
          }
    
    }
}
