package Barangay_Padolina;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Padolina Family
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BrgyPadolina extends javax.swing.JFrame {

    /**
     * Creates new form Test1
     */
    public BrgyPadolina() {
        initComponents();
        testConnection();
        showAllResidents();
        dt();
        times();

    }

    public void dt() {
        Date ds = new Date();

        SimpleDateFormat sd = new SimpleDateFormat("MM-dd-yyyy");

        String dd = sd.format(ds);

        jlbl_Date.setText(dd);

    }

    Timer t;
    SimpleDateFormat st;

    public void times() {

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

                Date dt = new Date();
                st = new SimpleDateFormat("hh:mm:ss");

                String tt = st.format(dt);
                jlbl_Time1.setText(tt);

            }
        });

        t.start();

    }

    Connection testConnection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/padolinasystem", "root", "");
            return connection;
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPnlTitle = new javax.swing.JPanel();
        jLblTitle1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLblIcon2 = new javax.swing.JLabel();
        jlblIcon1 = new javax.swing.JLabel();
        jPanelControl = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonReport = new javax.swing.JButton();
        jButtonAdding = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jButtonPermit = new javax.swing.JButton();
        jlblTime = new javax.swing.JLabel();
        jlbl_Date = new javax.swing.JLabel();
        jLblDate = new javax.swing.JLabel();
        jlbl_Time1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneSee = new javax.swing.JTabbedPane();
        jPanelHome1 = new javax.swing.JPanel();
        jLabelMission = new javax.swing.JLabel();
        jLabelVision = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMission = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextVision = new javax.swing.JTextArea();
        jPanelReport1 = new javax.swing.JPanel();
        jLblRprtsTitle = new javax.swing.JLabel();
        jbCapture = new javax.swing.JButton();
        jbCamera = new javax.swing.JButton();
        tbWebCam = new javax.swing.JToggleButton();
        tbCapture = new javax.swing.JToggleButton();
        jPanelAdd1 = new javax.swing.JPanel();
        jLblResidentInfoTitle = new javax.swing.JLabel();
        jLblFirstName = new javax.swing.JLabel();
        jLblMiddleName = new javax.swing.JLabel();
        jLblLastName = new javax.swing.JLabel();
        jLblGender = new javax.swing.JLabel();
        jLblDateOfBirth = new javax.swing.JLabel();
        jLblPlace = new javax.swing.JLabel();
        jTxtFldFirstName = new javax.swing.JTextField();
        jTxtFldMiddleName = new javax.swing.JTextField();
        jTxtFldLastName = new javax.swing.JTextField();
        jTxtFldGender = new javax.swing.JTextField();
        jTxtFldDateOfBirth = new javax.swing.JTextField();
        jTxtFldPLaceOfBirth = new javax.swing.JTextField();
        jLblCivilStatus = new javax.swing.JLabel();
        jLblCitizenship = new javax.swing.JLabel();
        jLblReligion = new javax.swing.JLabel();
        jLblOccupation = new javax.swing.JLabel();
        jTxtFldCivil = new javax.swing.JTextField();
        jTxtFldCitizenship = new javax.swing.JTextField();
        jTxtFldReligion = new javax.swing.JTextField();
        jTxtFldOccupation = new javax.swing.JTextField();
        jBttnAddInfo = new javax.swing.JButton();
        jPanelInfo1 = new javax.swing.JPanel();
        jLblResidentTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblResidentInfo = new javax.swing.JTable();
        bttnDelete = new javax.swing.JButton();
        bttnUpdate = new javax.swing.JButton();
        updateFname = new javax.swing.JTextField();
        updateMname = new javax.swing.JTextField();
        updateLname = new javax.swing.JTextField();
        updateGender = new javax.swing.JTextField();
        updateDoB = new javax.swing.JTextField();
        updatePoB = new javax.swing.JTextField();
        updateCivilStat = new javax.swing.JTextField();
        updateCitizenship = new javax.swing.JTextField();
        updateReligion = new javax.swing.JTextField();
        updateOccupation = new javax.swing.JTextField();
        upFname1 = new javax.swing.JLabel();
        upMname2 = new javax.swing.JLabel();
        upLname3 = new javax.swing.JLabel();
        upGender4 = new javax.swing.JLabel();
        upDoB5 = new javax.swing.JLabel();
        upPoB6 = new javax.swing.JLabel();
        upCivil7 = new javax.swing.JLabel();
        upCitizenship8 = new javax.swing.JLabel();
        upReligion9 = new javax.swing.JLabel();
        upOccupation10 = new javax.swing.JLabel();
        jPanelPermit1 = new javax.swing.JPanel();
        jLabelPermitTitle = new javax.swing.JLabel();
        choosePermit = new javax.swing.JComboBox<>();
        printButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelBackground.setBackground(new java.awt.Color(102, 102, 102));

        jPnlTitle.setBackground(new java.awt.Color(255, 255, 51));
        jPnlTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPnlTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblTitle1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLblTitle1.setText("Barangay Padolina Management System");
        jPnlTitle.add(jLblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 707, 70));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\x-mark-16.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPnlTitle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 30, 30));

        jLblIcon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\circle-cropped.png")); // NOI18N
        jPnlTitle.add(jLblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jlblIcon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\circle-cropped (1).png")); // NOI18N
        jPnlTitle.add(jlblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 110));

        jPanelControl.setBackground(new java.awt.Color(0, 153, 153));
        jPanelControl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanelControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonHome.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(51, 51, 51));
        jButtonHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\house-24.png")); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanelControl.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 248, 70));

        jButtonReport.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonReport.setForeground(new java.awt.Color(51, 51, 51));
        jButtonReport.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\report-2-24.png")); // NOI18N
        jButtonReport.setText("Report/Complains");
        jButtonReport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportActionPerformed(evt);
            }
        });
        jPanelControl.add(jButtonReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 248, 70));

        jButtonAdding.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAdding.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAdding.setForeground(new java.awt.Color(51, 51, 51));
        jButtonAdding.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\add-user-24.png")); // NOI18N
        jButtonAdding.setText("Add Resident");
        jButtonAdding.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddingActionPerformed(evt);
            }
        });
        jPanelControl.add(jButtonAdding, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 250, 70));

        jButtonInfo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInfo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonInfo.setForeground(new java.awt.Color(51, 51, 51));
        jButtonInfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\edit-user-24.png")); // NOI18N
        jButtonInfo.setText("Resident Information");
        jButtonInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanelControl.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 250, 60));

        jButtonPermit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPermit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonPermit.setForeground(new java.awt.Color(51, 51, 51));
        jButtonPermit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\report-3-24.png")); // NOI18N
        jButtonPermit.setText("Permits");
        jButtonPermit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonPermit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermitActionPerformed(evt);
            }
        });
        jPanelControl.add(jButtonPermit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 250, 59));

        jlblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTime.setText("Time:");
        jPanelControl.add(jlblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 63, 32));

        jlbl_Date.setBackground(new java.awt.Color(255, 0, 0));
        jlbl_Date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbl_Date.setForeground(new java.awt.Color(255, 0, 0));
        jPanelControl.add(jlbl_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 5, 118, 32));

        jLblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblDate.setText("Date:");
        jPanelControl.add(jLblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 5, 63, 32));

        jlbl_Time1.setBackground(new java.awt.Color(255, 0, 0));
        jlbl_Time1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbl_Time1.setForeground(new java.awt.Color(255, 0, 0));
        jPanelControl.add(jlbl_Time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 43, 118, 32));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneSee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jTabbedPaneSee.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jPanelHome1.setBackground(new java.awt.Color(0, 153, 153));

        jLabelMission.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelMission.setText("Mission");
        jLabelMission.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jLabelVision.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelVision.setText(" Vision");
        jLabelVision.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jTextMission.setEditable(false);
        jTextMission.setColumns(20);
        jTextMission.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jTextMission.setRows(5);
        jTextMission.setText("\n          Upang Maiwasan ang pagkaantala sa pagbibigay o \n          pagtugon sa pangangailangan o serbisyo\n          para sa mga residente o mamamayan ng barangay.");
        jTextMission.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jScrollPane1.setViewportView(jTextMission);

        jTextVision.setEditable(false);
        jTextVision.setColumns(20);
        jTextVision.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jTextVision.setRows(5);
        jTextVision.setText("   \n        Mabilis at Maagap na Serbisyong pampubliko sa maayos na \n        palilingkod para sa mga residente o mamayan ng Barangay.\n");
        jTextVision.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jScrollPane2.setViewportView(jTextVision);

        javax.swing.GroupLayout jPanelHome1Layout = new javax.swing.GroupLayout(jPanelHome1);
        jPanelHome1.setLayout(jPanelHome1Layout);
        jPanelHome1Layout.setHorizontalGroup(
            jPanelHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHome1Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(jPanelHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(jPanelHome1Layout.createSequentialGroup()
                .addGroup(jPanelHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHome1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabelVision, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHome1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabelMission)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHome1Layout.setVerticalGroup(
            jPanelHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVision, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabelMission)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneSee.addTab("              Home                ", jPanelHome1);

        jPanelReport1.setBackground(new java.awt.Color(0, 153, 153));

        jLblRprtsTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLblRprtsTitle.setText("Reports/Complains");
        jLblRprtsTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jbCapture.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbCapture.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\save-as-24.png")); // NOI18N
        jbCapture.setText("Save File");
        jbCapture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jbCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCaptureActionPerformed(evt);
            }
        });

        jbCamera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbCamera.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\camera-4-24.png")); // NOI18N
        jbCamera.setText("Capture");
        jbCamera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jbCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCameraActionPerformed(evt);
            }
        });

        tbWebCam.setBackground(new java.awt.Color(255, 255, 255));
        tbWebCam.setForeground(new java.awt.Color(102, 153, 255));
        tbWebCam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        tbCapture.setBackground(new java.awt.Color(255, 255, 255));
        tbCapture.setForeground(new java.awt.Color(102, 153, 255));
        tbCapture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        javax.swing.GroupLayout jPanelReport1Layout = new javax.swing.GroupLayout(jPanelReport1);
        jPanelReport1.setLayout(jPanelReport1Layout);
        jPanelReport1Layout.setHorizontalGroup(
            jPanelReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReport1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblRprtsTitle)
                .addGap(303, 303, 303))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReport1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanelReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbWebCam, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanelReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        jPanelReport1Layout.setVerticalGroup(
            jPanelReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReport1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblRprtsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanelReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbWebCam, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(tbCapture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(jPanelReport1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPaneSee.addTab("      Report           ", jPanelReport1);

        jPanelAdd1.setBackground(new java.awt.Color(0, 153, 153));

        jLblResidentInfoTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLblResidentInfoTitle.setText("Adding Residents Information");
        jLblResidentInfoTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLblFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblFirstName.setText("First Name:");

        jLblMiddleName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblMiddleName.setText("Middle Name:");

        jLblLastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblLastName.setText("Last Name:");

        jLblGender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblGender.setText("Gender:");

        jLblDateOfBirth.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblDateOfBirth.setText("Date of Birth:");

        jLblPlace.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblPlace.setText("Place of Birth:");

        jTxtFldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldFirstNameActionPerformed(evt);
            }
        });

        jTxtFldMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldMiddleNameActionPerformed(evt);
            }
        });

        jTxtFldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldLastNameActionPerformed(evt);
            }
        });

        jTxtFldGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldGenderActionPerformed(evt);
            }
        });

        jTxtFldDateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldDateOfBirthActionPerformed(evt);
            }
        });

        jTxtFldPLaceOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldPLaceOfBirthActionPerformed(evt);
            }
        });

        jLblCivilStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblCivilStatus.setText("Civil Status:");

        jLblCitizenship.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblCitizenship.setText("Citizenship:");

        jLblReligion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblReligion.setText("Religion:");

        jLblOccupation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLblOccupation.setText("Occupation:");

        jTxtFldCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldCivilActionPerformed(evt);
            }
        });

        jTxtFldCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldCitizenshipActionPerformed(evt);
            }
        });

        jTxtFldReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldReligionActionPerformed(evt);
            }
        });

        jTxtFldOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldOccupationActionPerformed(evt);
            }
        });

        jBttnAddInfo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBttnAddInfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\add-user-24.png")); // NOI18N
        jBttnAddInfo.setText("Add");
        jBttnAddInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jBttnAddInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdd1Layout = new javax.swing.GroupLayout(jPanelAdd1);
        jPanelAdd1.setLayout(jPanelAdd1Layout);
        jPanelAdd1Layout.setHorizontalGroup(
            jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdd1Layout.createSequentialGroup()
                        .addComponent(jTxtFldDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAdd1Layout.createSequentialGroup()
                        .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                                .addComponent(jLblOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                                .addComponent(jLblReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                                .addComponent(jLblCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                                .addComponent(jLblCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(jPanelAdd1Layout.createSequentialGroup()
                        .addComponent(jTxtFldPLaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBttnAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdd1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblResidentInfoTitle)
                .addGap(181, 181, 181))
        );
        jPanelAdd1Layout.setVerticalGroup(
            jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblResidentInfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdd1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdd1Layout.createSequentialGroup()
                        .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                                .addComponent(jTxtFldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtFldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAdd1Layout.createSequentialGroup()
                                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLblCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFldCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFldCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLblReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFldReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLblOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFldOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jTxtFldDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAdd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFldPLaceOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBttnAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jTabbedPaneSee.addTab("          Add       ", jPanelAdd1);

        jPanelInfo1.setBackground(new java.awt.Color(0, 153, 153));

        jLblResidentTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLblResidentTitle.setText("Residents Information");
        jLblResidentTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jTblResidentInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Middle Name", "Last Name", "Gender", "Date Of Birth", "Place Of Birth", "Civil Status", "Citizenship", "Religion", "Occupation"
            }
        ));
        jTblResidentInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblResidentInfoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTblResidentInfo);

        bttnDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bttnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\delete-24.png")); // NOI18N
        bttnDelete.setText("Delete");
        bttnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        bttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteActionPerformed(evt);
            }
        });

        bttnUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bttnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\available-updates-24.png")); // NOI18N
        bttnUpdate.setText("Update");
        bttnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        bttnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnUpdateMouseClicked(evt);
            }
        });
        bttnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdateActionPerformed(evt);
            }
        });

        updateFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFnameActionPerformed(evt);
            }
        });
        updateFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateFnameKeyTyped(evt);
            }
        });

        updateMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMnameActionPerformed(evt);
            }
        });
        updateMname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateMnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateMnameKeyTyped(evt);
            }
        });

        updateLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLnameActionPerformed(evt);
            }
        });
        updateLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateLnameKeyTyped(evt);
            }
        });

        updateGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGenderActionPerformed(evt);
            }
        });
        updateGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateGenderKeyTyped(evt);
            }
        });

        updateDoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoBActionPerformed(evt);
            }
        });
        updateDoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateDoBKeyTyped(evt);
            }
        });

        updatePoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updatePoBKeyTyped(evt);
            }
        });

        updateCivilStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCivilStatActionPerformed(evt);
            }
        });
        updateCivilStat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateCivilStatKeyTyped(evt);
            }
        });

        updateCitizenship.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateCitizenshipKeyTyped(evt);
            }
        });

        updateReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateReligionActionPerformed(evt);
            }
        });
        updateReligion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateReligionKeyTyped(evt);
            }
        });

        updateOccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateOccupationKeyTyped(evt);
            }
        });

        upFname1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upFname1.setText("     First Name:");

        upMname2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upMname2.setText(" Middle Name:");

        upLname3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upLname3.setText("     Last Name:");

        upGender4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upGender4.setText("         Gender:");

        upDoB5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upDoB5.setText("              DoB:");

        upPoB6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upPoB6.setText("              PoB:");

        upCivil7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upCivil7.setText("   Civil Status:");

        upCitizenship8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upCitizenship8.setText("   Citizenship:");

        upReligion9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upReligion9.setText("       Religion:");

        upOccupation10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        upOccupation10.setText(" Occupation:");

        javax.swing.GroupLayout jPanelInfo1Layout = new javax.swing.GroupLayout(jPanelInfo1);
        jPanelInfo1.setLayout(jPanelInfo1Layout);
        jPanelInfo1Layout.setHorizontalGroup(
            jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLblResidentTitle))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upPoB6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upDoB5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upGender4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upLname3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(upMname2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(upFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addComponent(updatePoB, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bttnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateMname, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateFname, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateLname, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateGender, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                                .addComponent(upReligion9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                                .addComponent(upOccupation10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                                .addComponent(upCitizenship8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                                .addComponent(upCivil7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateCivilStat, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))))
        );
        jPanelInfo1Layout.setVerticalGroup(
            jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblResidentTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateFname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateMname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upMname2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(upCivil7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCivilStat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upCitizenship8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateLname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upLname3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upReligion9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upGender4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upOccupation10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upDoB5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatePoB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upPoB6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInfo1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(jPanelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(195, 195, 195))
        );

        jTabbedPaneSee.addTab("                Info           ", jPanelInfo1);

        jPanelPermit1.setBackground(new java.awt.Color(0, 153, 153));

        jLabelPermitTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabelPermitTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelPermitTitle.setText("Permits");
        jLabelPermitTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        choosePermit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        choosePermit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barangay Clearance", "Barangay Indigency", "Travel Permit", " " }));
        choosePermit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        choosePermit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        choosePermit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choosePermitMouseClicked(evt);
            }
        });
        choosePermit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePermitActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        printButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Padolina Family\\Desktop\\Wendel1.2\\Barangay_Management_System\\Pictures\\printer-24.png")); // NOI18N
        printButton.setText("Print");
        printButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        printButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printButtonMouseClicked(evt);
            }
        });
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelPermit1Layout = new javax.swing.GroupLayout(jPanelPermit1);
        jPanelPermit1.setLayout(jPanelPermit1Layout);
        jPanelPermit1Layout.setHorizontalGroup(
            jPanelPermit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermit1Layout.createSequentialGroup()
                .addGroup(jPanelPermit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPermit1Layout.createSequentialGroup()
                        .addGroup(jPanelPermit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPermit1Layout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addComponent(jLabelPermitTitle))
                            .addGroup(jPanelPermit1Layout.createSequentialGroup()
                                .addGap(425, 425, 425)
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(choosePermit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelPermit1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPermit1Layout.setVerticalGroup(
            jPanelPermit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermit1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPermitTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanelPermit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choosePermit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jTabbedPaneSee.addTab("       Permit      ", jPanelPermit1);

        jPanel1.add(jTabbedPaneSee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 850, 680));

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPnlTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void showAllResidents() {
        try {
            String insert = "SELECT * FROM residents";
            Statement st = testConnection().createStatement();
            ResultSet rs = st.executeQuery(insert);
            Object[] fetchResidents = new Object[12];
            DefaultTableModel mod = (DefaultTableModel) jTblResidentInfo.getModel();
            while (rs.next()) {
                fetchResidents[0] = rs.getInt("ID");
                fetchResidents[1] = rs.getString("FIRSTNAME");
                fetchResidents[2] = rs.getString("MIDDLENAME");
                fetchResidents[3] = rs.getString("LASTNAME");
                fetchResidents[4] = rs.getString("GENDER");
                fetchResidents[5] = rs.getString("DOB");
                fetchResidents[6] = rs.getString("POB");
                fetchResidents[7] = rs.getString("CIVILSTATUS");
                fetchResidents[8] = rs.getString("CITIZENSHIP");
                fetchResidents[9] = rs.getString("RELIGION");
                fetchResidents[10] = rs.getString("OCCUPATION");
                mod.addRow(fetchResidents);

            }
        } catch (SQLException ex) {
            Logger.getLogger(BrgyPadolina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    int id;

    private void jButtonPermitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermitActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSee.setSelectedIndex(4);
    }//GEN-LAST:event_jButtonPermitActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSee.setSelectedIndex(3);
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddingActionPerformed
        jTabbedPaneSee.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonAddingActionPerformed

    private void jButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSee.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonReportActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        jTabbedPaneSee.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jbCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCaptureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCaptureActionPerformed

    private void jTxtFldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldFirstNameActionPerformed

    private void jTxtFldMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldMiddleNameActionPerformed

    private void jTxtFldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldLastNameActionPerformed

    private void jTxtFldGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldGenderActionPerformed

    private void jTxtFldDateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldDateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldDateOfBirthActionPerformed

    private void jTxtFldPLaceOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldPLaceOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldPLaceOfBirthActionPerformed

    private void jTxtFldCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldCivilActionPerformed

    private void jTxtFldCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldCitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldCitizenshipActionPerformed

    private void jTxtFldReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldReligionActionPerformed

    private void jTxtFldOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldOccupationActionPerformed

    private void jBttnAddInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddInfoActionPerformed

        try {
            String insert = "INSERT INTO `residents`(`FIRSTNAME`, `MIDDLENAME`, `LASTNAME`, `GENDER`, `DOB`, `POB`, `CIVILSTATUS`, `CITIZENSHIP`, `RELIGION`, `OCCUPATION`)VALUES(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st = testConnection().prepareStatement(insert);
            st.setString(1, jTxtFldFirstName.getText());
            st.setString(2, jTxtFldMiddleName.getText());
            st.setString(3, jTxtFldLastName.getText());
            st.setString(4, jTxtFldGender.getText());
            st.setString(5, jTxtFldDateOfBirth.getText());
            st.setString(6, jTxtFldPLaceOfBirth.getText());
            st.setString(7, jTxtFldCivil.getText());
            st.setString(8, jTxtFldCitizenship.getText());
            st.setString(9, jTxtFldReligion.getText());
            st.setString(10, jTxtFldOccupation.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Add Successfull");
        } catch (SQLException ex) {
            Logger.getLogger(BrgyPadolina.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jBttnAddInfoActionPerformed

    private void jTblResidentInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblResidentInfoMouseClicked
        id = (int) jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 0);
        jTxtFldFirstName.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 1).toString());
        jTxtFldMiddleName.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 2).toString());
        jTxtFldGender.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 4).toString());
        jTxtFldLastName.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 3).toString());
        jTxtFldDateOfBirth.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 5).toString());
        jTxtFldPLaceOfBirth.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 6).toString());
        jTxtFldCivil.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 7).toString());
        jTxtFldCitizenship.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 8).toString());
        jTxtFldReligion.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 9).toString());
        jTxtFldOccupation.setText(jTblResidentInfo.getValueAt(jTblResidentInfo.getSelectedRow(), 10).toString());
        JOptionPane.showMessageDialog(this, id);
    }//GEN-LAST:event_jTblResidentInfoMouseClicked

    private void bttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteActionPerformed
        try {
            String insert = "DELETE FROM residents where id = '" + id + "'";
            PreparedStatement st = testConnection().prepareStatement(insert);
            st.executeUpdate();
            DefaultTableModel mod = (DefaultTableModel) jTblResidentInfo.getModel();
            mod.setRowCount(0);
            showAllResidents();
        } catch (SQLException ex) {
            Logger.getLogger(BrgyPadolina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttnDeleteActionPerformed

    private void bttnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnUpdateMouseClicked

    private void bttnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdateActionPerformed
        try {
            String insert = "UPDATE residents SET`FIRSTNAME`=?, `MIDDLENAME`=?, `LASTNAME`=?, `GENDER`=?, `DOB`=?, `POB`=?, `CIVILSTATUS`=?, `CITIZENSHIP`=?, `RELIGION`=?, `OCCUPATION`=? where ID=?";
            PreparedStatement st = testConnection().prepareStatement(insert);
            st.setString(1, updateFname.getText());
            st.setString(2, updateMname.getText());
            st.setString(3, updateLname.getText());
            st.setString(4, updateGender.getText());
            st.setString(5, updateDoB.getText());
            st.setString(6, updatePoB.getText());
            st.setString(7, updateCivilStat.getText());
            st.setString(8, updateCitizenship.getText());
            st.setString(9, updateReligion.getText());
            st.setString(10, updateOccupation.getText());
            st.setInt(11, id);
            st.executeUpdate();
            DefaultTableModel mod = (DefaultTableModel) jTblResidentInfo.getModel();
            mod.setRowCount(0);
            showAllResidents();
            updateFname.setText("");
            updateMname.setText("");
            updateLname.setText("");
            updateGender.setText("");
            updateDoB.setText("");
            updatePoB.setText("");
            updateCivilStat.setText("");
            updateCitizenship.setText("");
            updateReligion.setText("");
            updateOccupation.setText("");

        } catch (SQLException ex) {
            Logger.getLogger(BrgyPadolina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttnUpdateActionPerformed

    private void updateFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateFnameActionPerformed

    private void updateMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMnameActionPerformed

    private void updateLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLnameActionPerformed

    private void updateGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateGenderActionPerformed

    private void updateDoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDoBActionPerformed

    private void updateCivilStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCivilStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateCivilStatActionPerformed

    private void updateReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateReligionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateMnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateMnameKeyPressed

    }//GEN-LAST:event_updateMnameKeyPressed

    private void updateMnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateMnameKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateMnameKeyTyped

    private void updateFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateFnameKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateFnameKeyTyped

    private void updateLnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateLnameKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateLnameKeyTyped

    private void updateGenderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateGenderKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateGenderKeyTyped

    private void updateDoBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateDoBKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= '0' && k <= '9')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateDoBKeyTyped

    private void updatePoBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updatePoBKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'Z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updatePoBKeyTyped

    private void updateCivilStatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateCivilStatKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'Z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateCivilStatKeyTyped

    private void updateCitizenshipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateCitizenshipKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'Z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateCitizenshipKeyTyped

    private void updateReligionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateReligionKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'Z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateReligionKeyTyped

    private void updateOccupationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateOccupationKeyTyped
        char k = evt.getKeyChar();
        if (!(k >= 'a' && k <= 'Z')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_updateOccupationKeyTyped

    private void jbCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCameraActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void printButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMouseClicked

    }//GEN-LAST:event_printButtonMouseClicked

    private void choosePermitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePermitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosePermitActionPerformed

    private void choosePermitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosePermitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choosePermitMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrgyPadolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrgyPadolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrgyPadolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrgyPadolina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrgyPadolina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnDelete;
    private javax.swing.JButton bttnUpdate;
    private javax.swing.JComboBox<String> choosePermit;
    private javax.swing.JButton jBttnAddInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdding;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonPermit;
    private javax.swing.JButton jButtonReport;
    private javax.swing.JLabel jLabelMission;
    private javax.swing.JLabel jLabelPermitTitle;
    private javax.swing.JLabel jLabelVision;
    private javax.swing.JLabel jLblCitizenship;
    private javax.swing.JLabel jLblCivilStatus;
    private javax.swing.JLabel jLblDate;
    private javax.swing.JLabel jLblDateOfBirth;
    private javax.swing.JLabel jLblFirstName;
    private javax.swing.JLabel jLblGender;
    private javax.swing.JLabel jLblIcon2;
    private javax.swing.JLabel jLblLastName;
    private javax.swing.JLabel jLblMiddleName;
    private javax.swing.JLabel jLblOccupation;
    private javax.swing.JLabel jLblPlace;
    private javax.swing.JLabel jLblReligion;
    private javax.swing.JLabel jLblResidentInfoTitle;
    private javax.swing.JLabel jLblResidentTitle;
    private javax.swing.JLabel jLblRprtsTitle;
    private javax.swing.JLabel jLblTitle1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAdd1;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelHome1;
    private javax.swing.JPanel jPanelInfo1;
    private javax.swing.JPanel jPanelPermit1;
    private javax.swing.JPanel jPanelReport1;
    private javax.swing.JPanel jPnlTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneSee;
    private javax.swing.JTable jTblResidentInfo;
    private javax.swing.JTextArea jTextMission;
    private javax.swing.JTextArea jTextVision;
    private javax.swing.JTextField jTxtFldCitizenship;
    private javax.swing.JTextField jTxtFldCivil;
    private javax.swing.JTextField jTxtFldDateOfBirth;
    private javax.swing.JTextField jTxtFldFirstName;
    private javax.swing.JTextField jTxtFldGender;
    private javax.swing.JTextField jTxtFldLastName;
    private javax.swing.JTextField jTxtFldMiddleName;
    private javax.swing.JTextField jTxtFldOccupation;
    private javax.swing.JTextField jTxtFldPLaceOfBirth;
    private javax.swing.JTextField jTxtFldReligion;
    private javax.swing.JButton jbCamera;
    private javax.swing.JButton jbCapture;
    private javax.swing.JLabel jlblIcon1;
    private javax.swing.JLabel jlblTime;
    private javax.swing.JLabel jlbl_Date;
    private javax.swing.JLabel jlbl_Time1;
    private javax.swing.JButton printButton;
    private javax.swing.JToggleButton tbCapture;
    private javax.swing.JToggleButton tbWebCam;
    private javax.swing.JLabel upCitizenship8;
    private javax.swing.JLabel upCivil7;
    private javax.swing.JLabel upDoB5;
    private javax.swing.JLabel upFname1;
    private javax.swing.JLabel upGender4;
    private javax.swing.JLabel upLname3;
    private javax.swing.JLabel upMname2;
    private javax.swing.JLabel upOccupation10;
    private javax.swing.JLabel upPoB6;
    private javax.swing.JLabel upReligion9;
    private javax.swing.JTextField updateCitizenship;
    private javax.swing.JTextField updateCivilStat;
    private javax.swing.JTextField updateDoB;
    private javax.swing.JTextField updateFname;
    private javax.swing.JTextField updateGender;
    private javax.swing.JTextField updateLname;
    private javax.swing.JTextField updateMname;
    private javax.swing.JTextField updateOccupation;
    private javax.swing.JTextField updatePoB;
    private javax.swing.JTextField updateReligion;
    // End of variables declaration//GEN-END:variables

}
